.\" (C) Copyright 2022 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH LINION 1 "Dezember 23 2022" "Project Linion" "Linion Addon Manager"
.SH ÜBERSICHT
linion \- TESO addon manager
.SH SYNOPSIS
.B linion
.RI [ Argumente ]
.SH BESCHREIBUNG
.B linion
ist ein Leichtgewichtsaddon manager für TESO. Etwas schneller als ihr Java Bruder. Eingestellt und eingeprüft auf Ubuntu Linux für TESO WINE Spieler
.PP
.SH ARGUMENTE
Dieses Programm folgt der üblichen GNU-Befehlszeilensyntax mit lang
Argumenten, die mit zwei Bindestrichen (`-') anfangen.
Eine Argumentenzusammenfassung finden Sie unten.
.TP
.B \-h, \-H, \-\-help
Argumentenzusammenfassung einzeigen
.TP
.B \-v, \-\-version
App Version einzeigen
