.\" (C) Copyright 2022 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH LINION 1 "December 16 2022" "Linion project" "Linion Addon Manager"
.SH NAME
linion \- TESO addon manager
.SH SYNOPSIS
.B linion
.RI [ options ]
.SH DESCRIPTION
.B linion
is a lightweight addon manager for TESO. Being smaller than its Java brother and built for those playing TESO on WINE
.PP
\fBlinion\fP is a program that...
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-H, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
