.\" (C) Copyright 2022 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH LINION 1 "December 16 2022" "Проект Linion" "Менеджер аддонов Linion"
.SH НАЗВАНИЕ
linion \- Менеджер аддонов для TESO Linion
.SH СИНТАКСИС
.B linion
.RI [ параметры ]
.SH ОПИСАНИЕ
.B linion
Менеджер аддонов для TESO, легче своего Java-собрата. Предназначен для тех, кто играет в TESO под WINE
.PP
.SH ПАРАМЕТРЫ
Программа соблюдает обычный для GNU команд синтаксис, включая параметры с двумя дефисами (`-').
Краткий список параметров предоставлен ниже.
.TP
.B \-h, \-H, \-\-help
Показать список параметров.
.TP
.B \-v, \-\-version
Показать текущую версию программмы.
